### ISSUE TITLE
CgroupDriver - Docker is used instead of CRI-O even though it is not installed

### ISSUE THREAD

**Issue by aendeavor** [kubernetes/kubeadm#2319]
## What keywords did you search in kubeadm issues before filing this one?

`cri-o`, `docker CRI-O cgroupdriver`

#2039 is somewhat related, but actually differs when it comes to the underlying problem.

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT (not 100% sure)

## Versions

``` JSON
// kubeadm version: &version.Info
{
  "Major": "1",
  "Minor": "19",
  "GitVersion": "v1.19.0",
  "GitCommit": "e19964183377d0ec2052d1f1fa930c4d7575bd50",
  "GitTreeState": "clean",
  "BuildDate": "2020-08-26T14:28:32Z",
  "GoVersion": "go1.15",
  "Compiler": "gc",
  "Platform": "linux/amd64"
}
```

#### Environment

``` JSON
// kubectl Client Version: version.Info
{
  "Major": "1",
  "Minor": "19",
  "GitVersion": "v1.19.2",
  "GitCommit": "f5743093fd1c663cb0cbc89748f730662345d44d",
  "GitTreeState": "clean",
  "BuildDate": "2020-09-16T13:41:02Z",
  "GoVersion": "go1.15",
  "Compiler": "gc",
  "Platform": "linux/amd64"
}
```

##### Cloud provider or hardware configuration

Running a control plane node and a worker node as virtual machines in KVM.

##### OS
``` BASH
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
##### Kernel

`Linux k8s-worker1 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

##### Others

``` YAML
# kubelet master conf
# generated  for and by kubeadm v1.19.2

apiVersion: kubeadm.k8s.io/v1beta2
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: zi68bn.lwwukbq2emz5pmmq
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  # advertiseAddress: 192.168.XXX.XXX
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///var/run/crio/crio.sock
  name: k8s-master
---
apiServer:
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta2
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controlPlaneEndpoint: cluster-endpoint:6443
controllerManager: {}
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: k8s.gcr.io
kind: ClusterConfiguration
kubernetesVersion: v1.19.2
networking:
  dnsDomain: cluster.local
  podSubnet: 192.167.0.0/16
  serviceSubnet: 10.96.0.0/12
scheduler: {}
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
```

## What happened?

I was installing `kubeadm` with `CRI-O` as the container runtime interface. After a lot of time spent I finally got it working, but when I came back the next day to proceed, I noticed the following: I was creating / listing tokens for workers to join. But when  executing 

``` BASH
$ kubeadm token create
```

I was greeted with

``` BASH
W1001 17:20:41.086691  126269 kubelet.go:200] cannot automatically set CgroupDriver when starting the Kubelet: cannot execute 'docker info -f {{.CgroupDriver}}': executable file not found in $PATH
W1001 17:20:41.090504  126269 configset.go:348] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
as6i4g.l28bjvdo6o8dxq4i
```

(the second warning is expected and will be removed with release `20.xx`)

I tried it as a normal (unpriviledged) user and with root: same result.

Strangely enough, there seems to be no problem with the cluster whatsoever...

## What you expected to (**not ?**) happen?

I did not expected to see this warning as

``` BASH
$ ls -lh /var/run/crio/crio.sock
```

yields

``` BASH
srwxr-xr-x 1 root root 0 Oct  1 11:00 /var/run/crio/crio.sock
```

which should be automatically detected by CRI, right? I never installed Docker and there is certainly no Docker socket open. The cgroupDriver should have already been set?!

## How to reproduce it (as minimally and precisely as possible)?

Follow [the docs for creating a cluster with kubeadm](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#join-nodes) using CRI-O as a container runtime.The configuration file used for `kubeadm init --config=/var/lib/kubelet/config.yaml` can be seen above.

## Anything else we need to know?

I really hope this is a misconfiguration on my side. If this is the case, sorry for the noise and thank's for the help.

**Comment by neolit123** [comment]
> W1001 17:20:41.086691  126269 kubelet.go:200] cannot automatically set CgroupDriver when starting the Kubelet: cannot execute 'docker info -f {{.CgroupDriver}}': executable file not found in $PATH

this is just a warning. socket != docker still tries to call `docker info` which was a bug.
https://github.com/kubernetes/kubeadm/issues/2270

but note that kubeadm supports detecting the cgroup driver only for docker.

> W1001 17:20:41.090504  126269 configset.go:348] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
as6i4g.l28bjvdo6o8dxq4i

this also also fixed here:
https://github.com/kubernetes/kubeadm/issues/2230

let me if there is anything else that i missed in the ticket
thanks
/close
/triage support

**Comment by aendeavor** [comment]
Thanks for the fast reply @neolit123 

> this is just a warning. socket != docker still tries to call `docker info` which was a bug.

Is this going to be fixed with the next versions then?

> but note that kubeadm supports detecting the cgroup driver only for docker.

Yeah I read about that. That's why I used the option in the configuration file. Is this the correct way?

**Comment by neolit123** [comment]
> Is this going to be fixed with the next versions then?

should be fixed for 1.20.

> Yeah I read about that. That's why I used the option in the configuration file. Is this the correct way?

yes, configuration file is preferred over the CLI flags.

**Comment by unixmind** [comment]
Dear all,
I'm running Kubernetes 1.20.5 (GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f") over CRI-O container runtime, and it is not fixed yet.
Regards
