### ISSUE TITLE
Incorrect version for kube-dns and CoreDNS

### ISSUE THREAD

**Issue by rajansandeep** [kubernetes/kubeadm#739]
## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
```
# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

## What happened?
kube-dns and CoreDNS don't provide the correct version number when looking up `kubeadm upgrade plan` to check the versions.

```
Upgrade to the latest stable version:

COMPONENT            CURRENT   AVAILABLE
API Server           v1.9.3    v1.10.0
Controller Manager   v1.9.3    v1.10.0
Scheduler            v1.9.3    v1.10.0
Kube Proxy           v1.9.3    v1.10.0
Kube DNS             1.14.7    1.14.7
Etcd                 3.1.11    3.1.11

```
```
Upgrade to the latest stable version:

COMPONENT            CURRENT   AVAILABLE
API Server           v1.9.6    v1.10.0
Controller Manager   v1.9.6    v1.10.0
Scheduler            v1.9.6    v1.10.0
Kube Proxy           v1.9.6    v1.10.0
CoreDNS              1.0.1     1.0.1
Etcd                 3.1.11    3.1.11


```

## What you expected to happen?
kube-dns and CoreDNS should show the correct version, i.e `1.14.8` and `1.0.6` respectively.

## How to reproduce it (as minimally and precisely as possible)?
`kubeadm upgrade plan` for kube-dns.
`kubeadm upgrade plan --feature-gates CoreDNS=true` for CoreDNS.

**Comment by bart0sh** [comment]
@rajansandeep 
kube-dns version was set to 1.14.8 in the commit [623ab15212](https://github.com/kubernetes/kubernetes/commit/623ab15212d466c1003c3a9196a933e336c707df)
coreDNS version was set to 1.0.6 in the commit [993e5413ce](https://github.com/kubernetes/kubernetes/commit/993e5413ce55d50e67e3f169671c5cec5458e5c2)

I can see both commits in v1.10.0

**Comment by chuckha** [comment]
@rajansandeep You'll have to use kubeadm v1.10 to see the new values -- what is the output when you upgrade kubeadm to version 1.10 (binary is available https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.10.md#server-binaries) and run upgrade plan?

**Comment by rajansandeep** [comment]
@chuckha I don't think the `kubeadm upgrade` issue is fixed, so I'm unable to check that yet.

**Comment by chuckha** [comment]
Oh, yeah you're totally right, it's not fixed yet.

Are you suggesting we backport/cherry-pick (which verb is correct?) those commits to 1.9.x? Seems reasonable if that's the version 1.10 wants...what do you think @timothysc ?

**Comment by chuckha** [comment]
After chatting in #sig-cluster-lifecycle it seems like the fix should be something like: don't suggest versions for versions ahead of current kubeadm. An example will make this clearer:

kubeadm (v1.9) upgrade plan says that v1.10.0 is the latest stable and also suggests that kube-dns should be version 1.14.7 for that upgrade. However, it also tells you to upgrade kubeadm to v1.10.0. Once you upgrade to v1.10.0 it will tell you that kube-dns should be 1.14.8.

We probably shouldn't be looking into the future and guess the wrong version for kube-dns (and other systems).

**Comment by praseodym** [comment]
kube-dns was upgraded to v1.14.10 https://github.com/kubernetes/kubernetes/pull/62678 in v1.9.7, but `kubeadm upgrade plan` with kubeadm v1.9.7 still keeps it at v1.14.7.

**Comment by chuckha** [comment]
@praseodym Good catch. I've opened a patch to get that cherry picked into the 1.9 release https://github.com/kubernetes/kubernetes/pull/63001

I'm working on a fix for the larger issue as well. This mostly comes down to not letting past versions of kubeadm try to read the future (hint: they cannot)

**Comment by chuckha** [comment]
@praseodym Looks like 1.9 won't be getting rev'd. Not sure about 1.10 though. Here are the relevant PRs.

1.9 cherry pick https://github.com/kubernetes/kubernetes/pull/63079
1.10 cherry pick https://github.com/kubernetes/kubernetes/pull/63081

Thanks for the report.
